---
- name: Launch EC2 instances in a private subnet
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: ap-southeast-1
    key_name: my-aws-key
    instance_type: t3.micro
    ami_id: ami-0abcdef1234567890
    private_subnet_id: subnet-0f77d7a495c138bd2
    security_group_id: sg-0726d659a82181af7
    count: 3  # 1 server, 2 agent nodes
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"  # Using environment variable
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"  # Using environment variable
  tasks:
    - name: Launch EC2 instances
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ private_subnet_id }}"
        group_id: "{{ security_group_id }}"
        count: "{{ count }}"
        instance_tags:
          Name: "k3s-node"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        wait: yes
      register: ec2

    - name: Add instances to inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"
      when: item.public_ip is defined

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      loop: "{{ ec2.instances }}"
      when: item.public_ip is defined
