---
- name: Launch EC2 instances in a private subnet
  hosts: localhost
  tasks:
    - name: Launch K3s server instance
      amazon.aws.ec2_instance:
        name: "k3s-server"
        key_name: zaman-key
        instance_type: t2.micro
        image_id: ami-060e277c0d4cce553
        region: ap-southeast-1
        wait: yes
        security_group: sg-0c94855b6f78de346
        subnet_id: subnet-08b71d05da928e641
        aws_access_key: AKIAXYKJQNVZRS2LB36Y
        aws_secret_key: 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
        network:
          assign_public_ip: yes  # Assign a public IP
      register: server_instance  # Register the output

    - name: Launch K3s agent instances
      amazon.aws.ec2_instance:
        name: "k3s-agent"
        count: 2
        key_name: zaman-key
        instance_type: t2.micro
        image_id: ami-060e277c0d4cce553
        region: ap-southeast-1
        wait: yes
        security_group: sg-0c94855b6f78de346
        subnet_id: subnet-08b71d05da928e641
        aws_access_key: AKIAXYKJQNVZRS2LB36Y
        aws_secret_key: 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
        network:
          assign_public_ip: yes  # Assign a public IP
      register: agent_instances  # Register the output

    - name: Update inventory file
      block:
        - name: Add server to inventory
          lineinfile:
            path: inventory.ini
            line: "k3s_server ansible_host={{ server_instance.instances[0].public_ip_address }} ansible_user=ec2-user ansible_ssh_private_key_file=/workspaces/k3s-aws-api-deployment/k3s-setup/ssh-key/zaman-key.pem"
            create: yes

        - name: Add agents to inventory
          lineinfile:
            path: inventory.ini
            line: "k3s_agent ansible_host={{ item.public_ip_address }} ansible_user=ec2-user ansible_ssh_private_key_file=/workspaces/k3s-aws-api-deployment/k3s-setup/ssh-key/zaman-key.pem"
          loop: "{{ agent_instances.instances }}"
